name: Deploy To Apache Server
run-name: Deploying to Apache Server by @${{ github.actor }}
on:
  push:
    branches:
      - 'main'
    paths:
      - 'code/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "code/*"
          target: $${ secrets.TARGET_PATH_DEFAULT }}
